name: .NET

on:
  push:
    branches:
    - develop
    
env:
  buildConfiguration: 'Release'
  buildRuntime: 'win-x64'
  runEnvironment: 'Pipeline'
  
jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Restore dependencies
      run: dotnet restore ${{ github.workspace }}\Source\Register.sln
      
    - name: Build
      run: dotnet build ${{ github.workspace }}\Source\Register.sln --configuration ${{ env.buildConfiguration }}
      
#     - name: Unit Tests
#       run: |
#         $vsTestConsoleExe = "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\Extensions\TestPlatform\vstest.console.exe"
#         $targetTestDll = "`"${{ github.workspace }}\Source\CDR.Register.API.Infrastructure.Tests.UnitTests\bin\Release\net5.0\CDR.Register.API.Infrastructure.Tests.UnitTests.dll`" `"${{ github.workspace }}\Source\CDR.Register.Domain.UnitTests\bin\Release\net5.0\CDR.Register.Domain.UnitTests.dll`" `"${{ github.workspace }}\Source\CDR.Register.IdentityServer.Tests.UnitTests\bin\Release\net5.0\CDR.Register.IdentityServer.Tests.UnitTests.dll`" `"${{ github.workspace }}\Source\CDR.Register.SSA.API.UnitTests\bin\Release\net5.0\CDR.Register.SSA.API.UnitTests.dll`""
#         #Note that the `" is an escape character to quote strings, and the `& is needed to start the command
#         $command = "`& `"$vsTestConsoleExe`" $targetTestDll"
#         Write-Host "$command"
#         Invoke-Expression $command
#       shell: powershell
      
    - name: Publish
      run: |
        dotnet publish ${{ github.workspace }}\Source\CDR.Register.API.Gateway.TLS --configuration ${{ env.buildConfiguration }} --runtime ${{ env.buildRuntime }} --no-restore --self-contained true 
        dotnet publish ${{ github.workspace }}\Source\CDR.Register.API.Gateway.mTLS --configuration ${{ env.buildConfiguration }} --runtime ${{ env.buildRuntime }} --no-restore --self-contained true 
        dotnet publish ${{ github.workspace }}\Source\CDR.Register.Admin.API --configuration ${{ env.buildConfiguration }} --runtime ${{ env.buildRuntime }} --no-restore --self-contained true 
        dotnet publish ${{ github.workspace }}\Source\CDR.Register.Discovery.API --configuration ${{ env.buildConfiguration }} --runtime ${{ env.buildRuntime }} --no-restore --self-contained true 
        dotnet publish ${{ github.workspace }}\Source\CDR.Register.IdentityServer --configuration ${{ env.buildConfiguration }} --runtime ${{ env.buildRuntime }} --no-restore --self-contained true
        dotnet publish ${{ github.workspace }}\Source\CDR.Register.SSA.API --configuration ${{ env.buildConfiguration }} --runtime ${{ env.buildRuntime }} --no-restore --self-contained true 
        dotnet publish ${{ github.workspace }}\Source\CDR.Register.Status.API --configuration ${{ env.buildConfiguration }} --runtime ${{ env.buildRuntime }} --no-restore --self-contained true 
      
    - name: Install root certificate
      run: |
        # Write your PowerShell commands here.
        $PlainPassword = "#M0ckCDRCA#" 
        $SecurePassword = $PlainPassword | ConvertTo-SecureString -AsPlainText -Force
        Import-PfxCertificate -Password $SecurePassword -FilePath "CertificateManagement/mtls/ca.pfx" -CertStoreLocation Cert:\LocalMachine\Root
      shell: powershell
      
    - name: Integration Tests
      run: |
        echo ${{ github.workspace }}
        
        cd ${{ github.workspace }}
        dir
        cd Source\CDR.Register.Admin.API\bin\Release\net5.0\win-x64
        Start-Process -FilePath "CDR.Register.Admin.API.exe" -WindowStyle Hidden
        cd ${{ github.workspace }}
        
        cd Source\CDR.Register.Status.API\bin\Release\net5.0\win-x64
        Start-Process -FilePath "CDR.Register.Status.API.exe" -WindowStyle Hidden
        cd ${{ github.workspace }}
        
        cd Source\CDR.Register.Discovery.API\bin\Release\net5.0\win-x64
        Start-Process -FilePath "CDR.Register.Discovery.API.exe" -WindowStyle Hidden
        cd ${{ github.workspace }}
        
        cd Source\CDR.Register.SSA.API\bin\Release\net5.0\win-x64
        Start-Process -FilePath "CDR.Register.SSA.API.exe" -WindowStyle Hidden
        cd ${{ github.workspace }}
        
        cd Source\CDR.Register.API.Gateway.mTLS\bin\Release\net5.0\win-x64
        Start-Process -FilePath "CDR.Register.API.Gateway.mTLS.exe" -WindowStyle Hidden
        cd ${{ github.workspace }}
        
        cd Source\CDR.Register.API.Gateway.TLS\bin\Release\net5.0\win-x64
        Start-Process -FilePath "CDR.Register.API.Gateway.TLS.exe" -WindowStyle Hidden
        cd ${{ github.workspace }}
        
        cd Source\CDR.Register.IdentityServer\bin\Release\net5.0\win-x64
        Start-Process -FilePath "CDR.Register.IdentityServer.exe" -WindowStyle Hidden

        Write-Host "Sleeping for 20 seconds..."
        Start-Sleep 20
        
        [System.Net.ServicePointManager]::ServerCertificateValidationCallback = { $True }
        
        Write-Host "curl 0"
        $apiReq = [System.Net.HttpWebRequest]::CreateHttp("https://localhost:7000/idp/.well-known/openid-configuration")
        $apiRes = $apiReq.GetResponse()
        Write-Host $apiRes
        
        Write-Host "curl 1"
        $apiReq = [System.Net.HttpWebRequest]::CreateHttp("https://localhost:7000/cdr-register/v1/banking/data-recipients")
        $apiRes = $apiReq.GetResponse()
        Write-Host $apiRes.StatusCode
        
        Write-Host "curl 2"
        $apiReq = [System.Net.HttpWebRequest]::CreateHttp("https://127.0.0.1:7000/cdr-register/v1/banking/data-recipients")
        $apiRes = $apiReq.GetResponse()
        Write-Host $apiRes
        
        $vsTestConsoleExe = "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\Extensions\TestPlatform\vstest.console.exe"
        $targetTestDll = "${{ github.workspace }}\Source\CDR.Register.IntegrationTests\bin\Release\net5.0\win-x64\CDR.Register.IntegrationTests.dll"
        $testRunSettings = "/Settings:`"${{ github.workspace }}\Source\CDR.Register.IntegrationTests\integration.runsettings`" "
        #Note that the `" is an escape character to quote strings, and the `& is needed to start the command
        $command = "`& `"$vsTestConsoleExe`" `"$targetTestDll`" $testRunSettings $parameters"
        Write-Host "$command"
        Invoke-Expression $command
      shell: powershell
